// stream_dma_v2_core.sv — Simplified DUT using vTen SV interfaces
// AXI-Lite controller is auto-generated by vTen (generate_controller: true)
// Registers are exposed as simple signals.

module stream_dma_v2_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_dst_addr_lo,
    input  logic [31:0] reg_dst_addr_hi,
    input  logic [31:0] reg_length,
    input  logic        reg_ctrl,          // pulse: 1-cycle start trigger
    output logic        reg_status,        // read-only: done flag

    // ── AXI4-Stream Slave (SV interface) ──
    vten_axis_if.slave   input_stream,

    // ── AXI4 Master (SV interface) ──
    vten_aximm_if.master dma_port
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;

    // AXI4 Read — tie off (unused)
    assign dma_port.araddr  = '0;
    assign dma_port.arlen   = '0;
    assign dma_port.arsize  = '0;
    assign dma_port.arburst = '0;
    assign dma_port.arvalid = 1'b0;
    assign dma_port.rready  = 1'b0;

    // ── DMA Engine ──
    typedef enum logic [2:0] {
        DMA_IDLE,
        DMA_ACCEPT_STREAM,
        DMA_WRITE_AW,
        DMA_WRITE_W,
        DMA_WAIT_B,
        DMA_DONE
    } dma_state_t;

    dma_state_t            dma_state;
    logic [ADDR_W-1:0]     dma_dst_addr;
    int                    dma_beats_left;
    int                    dma_beat_count;
    logic [DATA_W-1:0]     dma_data_latch;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            dma_state            <= DMA_IDLE;
            input_stream.tready  <= 1'b0;
            dma_port.awvalid     <= 1'b0;
            dma_port.wvalid      <= 1'b0;
            dma_port.bready      <= 1'b0;
            reg_status           <= 1'b0;
            dma_beat_count       <= 0;
        end else begin
            case (dma_state)
                DMA_IDLE: begin
                    input_stream.tready <= 1'b0;
                    if (reg_ctrl) begin
                        dma_dst_addr   <= {reg_dst_addr_hi, reg_dst_addr_lo};
                        dma_beats_left <= reg_length;
                        dma_beat_count <= 0;
                        reg_status     <= 1'b0;
                        if (reg_length == 0)
                            dma_state <= DMA_DONE;
                        else begin
                            dma_state           <= DMA_ACCEPT_STREAM;
                            input_stream.tready <= 1'b1;
                        end
                    end
                end

                DMA_ACCEPT_STREAM: begin
                    if (input_stream.tvalid && input_stream.tready) begin
                        dma_data_latch      <= input_stream.tdata;
                        input_stream.tready <= 1'b0;
                        dma_state           <= DMA_WRITE_AW;
                    end
                end

                DMA_WRITE_AW: begin
                    dma_port.awaddr  <= dma_dst_addr + dma_beat_count * BYTES_PER_BEAT;
                    dma_port.awlen   <= 8'd0;
                    dma_port.awsize  <= $clog2(BYTES_PER_BEAT);
                    dma_port.awburst <= 2'b01;
                    dma_port.awvalid <= 1'b1;
                    dma_port.wdata   <= dma_data_latch;
                    dma_port.wstrb   <= {BYTES_PER_BEAT{1'b1}};
                    dma_port.wlast   <= 1'b1;
                    dma_port.wvalid  <= 1'b1;
                    dma_state        <= DMA_WRITE_W;
                end

                DMA_WRITE_W: begin
                    if (dma_port.awready && dma_port.awvalid)
                        dma_port.awvalid <= 1'b0;
                    if (dma_port.wready && dma_port.wvalid)
                        dma_port.wvalid <= 1'b0;

                    if ((!dma_port.awvalid || dma_port.awready) &&
                        (!dma_port.wvalid  || dma_port.wready)) begin
                        dma_port.awvalid <= 1'b0;
                        dma_port.wvalid  <= 1'b0;
                        dma_port.bready  <= 1'b1;
                        dma_state        <= DMA_WAIT_B;
                    end
                end

                DMA_WAIT_B: begin
                    if (dma_port.bvalid && dma_port.bready) begin
                        dma_port.bready <= 1'b0;
                        dma_beat_count  <= dma_beat_count + 1;
                        dma_beats_left  <= dma_beats_left - 1;
                        if (dma_beats_left == 1)
                            dma_state <= DMA_DONE;
                        else begin
                            input_stream.tready <= 1'b1;
                            dma_state           <= DMA_ACCEPT_STREAM;
                        end
                    end
                end

                DMA_DONE: begin
                    reg_status <= 1'b1;
                    dma_state  <= DMA_IDLE;
                end
            endcase
        end
    end

endmodule
