// stream_scatter_core.sv — Streaming scatter to dual HBM ports
// Receives AXI4-Stream input, scales each element by 2 (saturating),
// then distributes beats alternately to hbm_0 (even beats) and hbm_1 (odd beats).
// AXI4-Lite controller is auto-generated by vTen (generate_controller: true)

module stream_scatter_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_dst0_addr_lo,
    input  logic [31:0] reg_dst0_addr_hi,
    input  logic [31:0] reg_dst1_addr_lo,
    input  logic [31:0] reg_dst1_addr_hi,
    input  logic [31:0] reg_length,         // total number of input beats
    input  logic        reg_ctrl,           // pulse: start
    output logic        reg_status,         // done flag
    output logic [31:0] reg_beat_count,     // processed beats (readable)

    // ── AXI4-Stream Slave (input) ──
    vten_axis_if.slave   input_stream,

    // ── AXI4 Master port 0 (hbm_0, even beats) ──
    vten_aximm_if.master hbm_0,

    // ── AXI4 Master port 1 (hbm_1, odd beats) ──
    vten_aximm_if.master hbm_1
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;
    localparam int ELEMS_PER_BEAT = DATA_W / 8;  // 8-bit elements

    // ── State machine ──
    typedef enum logic [3:0] {
        S_IDLE,
        S_ACCEPT,       // Accept one stream beat
        S_PROCESS,      // Scale data (1 cycle)
        S_WRITE_AW,     // Issue AW on selected port
        S_WRITE_W,      // Send W data
        S_WRITE_B,      // Wait B response
        S_DONE
    } state_t;

    state_t                state;
    logic [ADDR_W-1:0]     dst0_addr;
    logic [ADDR_W-1:0]     dst1_addr;
    int                    total_beats;
    int                    beat_idx;
    int                    port0_beat;      // count of beats written to port 0
    int                    port1_beat;      // count of beats written to port 1

    logic [DATA_W-1:0]     stream_data;
    logic [DATA_W-1:0]     scaled_data;
    logic                  use_port1;       // 0 = hbm_0, 1 = hbm_1

    // ── ALU: element-wise scale by 2 (signed saturating) ──
    always_comb begin
        for (int i = 0; i < ELEMS_PER_BEAT; i++) begin
            logic signed [8:0] val, doubled;
            val = 9'(signed'(stream_data[i*8 +: 8]));
            doubled = val <<< 1;
            if (doubled > 127)
                scaled_data[i*8 +: 8] = 8'sd127;
            else if (doubled < -128)
                scaled_data[i*8 +: 8] = 8'(-128);
            else
                scaled_data[i*8 +: 8] = doubled[7:0];
        end
    end

    // ── Tie off read channels (unused — DUT only writes) ──
    assign hbm_0.araddr  = '0;
    assign hbm_0.arlen   = '0;
    assign hbm_0.arsize  = '0;
    assign hbm_0.arburst = '0;
    assign hbm_0.arvalid = 1'b0;
    assign hbm_0.rready  = 1'b0;

    assign hbm_1.araddr  = '0;
    assign hbm_1.arlen   = '0;
    assign hbm_1.arsize  = '0;
    assign hbm_1.arburst = '0;
    assign hbm_1.arvalid = 1'b0;
    assign hbm_1.rready  = 1'b0;

    // ── AXI4 write mux signals ──
    // Selected port's AW/W/B signals
    logic [ADDR_W-1:0] wr_awaddr;
    logic               wr_awvalid, wr_awready;
    logic [DATA_W-1:0]  wr_wdata;
    logic               wr_wvalid, wr_wready;
    logic               wr_bvalid, wr_bready;

    // Port mux: route write transactions to selected port
    always_comb begin
        // Defaults: both ports idle
        hbm_0.awaddr  = '0;
        hbm_0.awlen   = '0;
        hbm_0.awsize  = $clog2(BYTES_PER_BEAT);
        hbm_0.awburst = 2'b01;
        hbm_0.awvalid = 1'b0;
        hbm_0.wdata   = '0;
        hbm_0.wstrb   = '0;
        hbm_0.wlast   = 1'b0;
        hbm_0.wvalid  = 1'b0;
        hbm_0.bready  = 1'b0;

        hbm_1.awaddr  = '0;
        hbm_1.awlen   = '0;
        hbm_1.awsize  = $clog2(BYTES_PER_BEAT);
        hbm_1.awburst = 2'b01;
        hbm_1.awvalid = 1'b0;
        hbm_1.wdata   = '0;
        hbm_1.wstrb   = '0;
        hbm_1.wlast   = 1'b0;
        hbm_1.wvalid  = 1'b0;
        hbm_1.bready  = 1'b0;

        wr_awready = 1'b0;
        wr_wready  = 1'b0;
        wr_bvalid  = 1'b0;

        if (!use_port1) begin
            hbm_0.awaddr  = wr_awaddr;
            hbm_0.awvalid = wr_awvalid;
            hbm_0.wdata   = wr_wdata;
            hbm_0.wstrb   = {BYTES_PER_BEAT{1'b1}};
            hbm_0.wlast   = 1'b1;
            hbm_0.wvalid  = wr_wvalid;
            hbm_0.bready  = wr_bready;
            wr_awready    = hbm_0.awready;
            wr_wready     = hbm_0.wready;
            wr_bvalid     = hbm_0.bvalid;
        end else begin
            hbm_1.awaddr  = wr_awaddr;
            hbm_1.awvalid = wr_awvalid;
            hbm_1.wdata   = wr_wdata;
            hbm_1.wstrb   = {BYTES_PER_BEAT{1'b1}};
            hbm_1.wlast   = 1'b1;
            hbm_1.wvalid  = wr_wvalid;
            hbm_1.bready  = wr_bready;
            wr_awready    = hbm_1.awready;
            wr_wready     = hbm_1.wready;
            wr_bvalid     = hbm_1.bvalid;
        end
    end

    // ── Main FSM ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state              <= S_IDLE;
            input_stream.tready <= 1'b0;
            reg_status         <= 1'b0;
            reg_beat_count     <= 32'd0;
            beat_idx           <= 0;
            port0_beat         <= 0;
            port1_beat         <= 0;
            wr_awaddr          <= '0;
            wr_awvalid         <= 1'b0;
            wr_wdata           <= '0;
            wr_wvalid          <= 1'b0;
            wr_bready          <= 1'b0;
            use_port1          <= 1'b0;
        end else begin
            case (state)
                S_IDLE: begin
                    input_stream.tready <= 1'b0;
                    if (reg_ctrl) begin
                        dst0_addr      <= {reg_dst0_addr_hi, reg_dst0_addr_lo};
                        dst1_addr      <= {reg_dst1_addr_hi, reg_dst1_addr_lo};
                        total_beats    <= reg_length;
                        beat_idx       <= 0;
                        port0_beat     <= 0;
                        port1_beat     <= 0;
                        reg_status     <= 1'b0;
                        reg_beat_count <= 32'd0;
                        if (reg_length == 0)
                            state <= S_DONE;
                        else begin
                            state              <= S_ACCEPT;
                            input_stream.tready <= 1'b1;
                        end
                    end
                end

                S_ACCEPT: begin
                    if (input_stream.tvalid && input_stream.tready) begin
                        stream_data         <= input_stream.tdata;
                        input_stream.tready <= 1'b0;
                        use_port1           <= beat_idx[0];  // even→port0, odd→port1
                        state               <= S_PROCESS;
                    end
                end

                S_PROCESS: begin
                    // scaled_data ready from comb ALU
                    state <= S_WRITE_AW;
                end

                S_WRITE_AW: begin
                    if (!use_port1) begin
                        wr_awaddr <= dst0_addr + port0_beat * BYTES_PER_BEAT;
                    end else begin
                        wr_awaddr <= dst1_addr + port1_beat * BYTES_PER_BEAT;
                    end
                    wr_awvalid <= 1'b1;
                    wr_wdata   <= scaled_data;
                    wr_wvalid  <= 1'b1;
                    state      <= S_WRITE_W;
                end

                S_WRITE_W: begin
                    if (wr_awready && wr_awvalid)
                        wr_awvalid <= 1'b0;
                    if (wr_wready && wr_wvalid)
                        wr_wvalid <= 1'b0;

                    if ((!wr_awvalid || wr_awready) &&
                        (!wr_wvalid  || wr_wready)) begin
                        wr_awvalid <= 1'b0;
                        wr_wvalid  <= 1'b0;
                        wr_bready  <= 1'b1;
                        state      <= S_WRITE_B;
                    end
                end

                S_WRITE_B: begin
                    if (wr_bvalid && wr_bready) begin
                        wr_bready      <= 1'b0;
                        beat_idx       <= beat_idx + 1;
                        reg_beat_count <= beat_idx + 1;

                        if (!use_port1)
                            port0_beat <= port0_beat + 1;
                        else
                            port1_beat <= port1_beat + 1;

                        if (beat_idx + 1 >= total_beats)
                            state <= S_DONE;
                        else begin
                            input_stream.tready <= 1'b1;
                            state               <= S_ACCEPT;
                        end
                    end
                end

                S_DONE: begin
                    reg_status <= 1'b1;
                    state      <= S_IDLE;
                end
            endcase
        end
    end

endmodule
