// vector_alu_core.sv — Vector ALU accelerator DUT
// Reads operand A and B from DDR via AXI4, computes result, writes back via AXI4.
// Operation mode: 0=ADD, 1=SUB, 2=MUL (element-wise, 8-bit saturating)
// AXI4-Lite controller is auto-generated by vTen (generate_controller: true)

module vector_alu_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_src_a_addr_lo,
    input  logic [31:0] reg_src_a_addr_hi,
    input  logic [31:0] reg_src_b_addr_lo,
    input  logic [31:0] reg_src_b_addr_hi,
    input  logic [31:0] reg_dst_addr_lo,
    input  logic [31:0] reg_dst_addr_hi,
    input  logic [31:0] reg_length,        // number of beats
    input  logic [31:0] reg_op_mode,       // 0=ADD, 1=SUB, 2=MUL
    input  logic        reg_ctrl,          // pulse: 1-cycle start trigger
    output logic        reg_status,        // read-only: done flag

    // ── AXI4 Master (SV interface) — single port for read A, read B, write result ──
    vten_aximm_if.master mem_port
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;
    localparam int ELEMS_PER_BEAT = DATA_W / 8;  // 8-bit elements

    // ── State machine ──
    typedef enum logic [3:0] {
        S_IDLE,
        S_READ_A_AR,       // Issue AR for operand A
        S_READ_A_R,        // Receive R for operand A
        S_READ_B_AR,       // Issue AR for operand B
        S_READ_B_R,        // Receive R for operand B
        S_COMPUTE,         // Element-wise ALU
        S_WRITE_AW,        // Issue AW for result
        S_WRITE_W,         // Send W data
        S_WRITE_B,         // Wait for B response
        S_DONE
    } state_t;

    state_t                state;
    logic [ADDR_W-1:0]     src_a_addr;
    logic [ADDR_W-1:0]     src_b_addr;
    logic [ADDR_W-1:0]     dst_addr;
    int                    beats_total;
    int                    beat_idx;
    logic [1:0]            op_mode;

    logic [DATA_W-1:0]     data_a;
    logic [DATA_W-1:0]     data_b;
    logic [DATA_W-1:0]     data_result;

    // ── ALU: element-wise 8-bit operation ──
    always_comb begin
        for (int i = 0; i < ELEMS_PER_BEAT; i++) begin
            logic signed [8:0] a_val, b_val, res;
            a_val = 9'(signed'(data_a[i*8 +: 8]));
            b_val = 9'(signed'(data_b[i*8 +: 8]));
            case (op_mode)
                2'd0: res = a_val + b_val;                          // ADD
                2'd1: res = a_val - b_val;                          // SUB
                2'd2: res = 9'(signed'(data_a[i*8 +: 8]) *
                            signed'(data_b[i*8 +: 8]));             // MUL (low 8-bit)
                default: res = a_val + b_val;
            endcase
            // Saturating clamp to [-128, 127]
            if (op_mode != 2'd2) begin
                if (res > 127)  data_result[i*8 +: 8] = 8'sd127;
                else if (res < -128) data_result[i*8 +: 8] = 8'(-128);
                else data_result[i*8 +: 8] = res[7:0];
            end else begin
                data_result[i*8 +: 8] = res[7:0];  // MUL: take low 8 bits
            end
        end
    end

    // ── Default tie-offs (overridden in relevant states) ──
    // Read channel defaults
    always_comb begin
        // These are driven in the FSM via always_ff;
        // tie off unused write-back from comb
    end

    // ── Main FSM ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state          <= S_IDLE;
            reg_status     <= 1'b0;
            beat_idx       <= 0;
            // AXI4 defaults
            mem_port.arvalid <= 1'b0;
            mem_port.rready  <= 1'b0;
            mem_port.awvalid <= 1'b0;
            mem_port.wvalid  <= 1'b0;
            mem_port.bready  <= 1'b0;
        end else begin
            case (state)
                // ────────────────────────────────────────────
                S_IDLE: begin
                    if (reg_ctrl) begin
                        src_a_addr  <= {reg_src_a_addr_hi, reg_src_a_addr_lo};
                        src_b_addr  <= {reg_src_b_addr_hi, reg_src_b_addr_lo};
                        dst_addr    <= {reg_dst_addr_hi, reg_dst_addr_lo};
                        beats_total <= reg_length;
                        op_mode     <= reg_op_mode[1:0];
                        beat_idx    <= 0;
                        reg_status  <= 1'b0;
                        if (reg_length == 0)
                            state <= S_DONE;
                        else
                            state <= S_READ_A_AR;
                    end
                end

                // ── Read operand A ──
                S_READ_A_AR: begin
                    mem_port.araddr  <= src_a_addr + beat_idx * BYTES_PER_BEAT;
                    mem_port.arlen   <= 8'd0;       // single beat
                    mem_port.arsize  <= $clog2(BYTES_PER_BEAT);
                    mem_port.arburst <= 2'b01;       // INCR
                    mem_port.arvalid <= 1'b1;
                    state            <= S_READ_A_R;
                end

                S_READ_A_R: begin
                    if (mem_port.arready && mem_port.arvalid)
                        mem_port.arvalid <= 1'b0;

                    mem_port.rready <= 1'b1;
                    if (mem_port.rvalid && mem_port.rready) begin
                        data_a           <= mem_port.rdata;
                        mem_port.rready  <= 1'b0;
                        state            <= S_READ_B_AR;
                    end
                end

                // ── Read operand B ──
                S_READ_B_AR: begin
                    mem_port.araddr  <= src_b_addr + beat_idx * BYTES_PER_BEAT;
                    mem_port.arlen   <= 8'd0;
                    mem_port.arsize  <= $clog2(BYTES_PER_BEAT);
                    mem_port.arburst <= 2'b01;
                    mem_port.arvalid <= 1'b1;
                    state            <= S_READ_B_R;
                end

                S_READ_B_R: begin
                    if (mem_port.arready && mem_port.arvalid)
                        mem_port.arvalid <= 1'b0;

                    mem_port.rready <= 1'b1;
                    if (mem_port.rvalid && mem_port.rready) begin
                        data_b           <= mem_port.rdata;
                        mem_port.rready  <= 1'b0;
                        state            <= S_COMPUTE;
                    end
                end

                // ── Compute (1 cycle — result ready from comb ALU) ──
                S_COMPUTE: begin
                    state <= S_WRITE_AW;
                end

                // ── Write result ──
                S_WRITE_AW: begin
                    mem_port.awaddr  <= dst_addr + beat_idx * BYTES_PER_BEAT;
                    mem_port.awlen   <= 8'd0;
                    mem_port.awsize  <= $clog2(BYTES_PER_BEAT);
                    mem_port.awburst <= 2'b01;
                    mem_port.awvalid <= 1'b1;
                    mem_port.wdata   <= data_result;
                    mem_port.wstrb   <= {BYTES_PER_BEAT{1'b1}};
                    mem_port.wlast   <= 1'b1;
                    mem_port.wvalid  <= 1'b1;
                    state            <= S_WRITE_W;
                end

                S_WRITE_W: begin
                    if (mem_port.awready && mem_port.awvalid)
                        mem_port.awvalid <= 1'b0;
                    if (mem_port.wready && mem_port.wvalid)
                        mem_port.wvalid <= 1'b0;

                    if ((!mem_port.awvalid || mem_port.awready) &&
                        (!mem_port.wvalid  || mem_port.wready)) begin
                        mem_port.awvalid <= 1'b0;
                        mem_port.wvalid  <= 1'b0;
                        mem_port.bready  <= 1'b1;
                        state            <= S_WRITE_B;
                    end
                end

                S_WRITE_B: begin
                    if (mem_port.bvalid && mem_port.bready) begin
                        mem_port.bready <= 1'b0;
                        beat_idx        <= beat_idx + 1;
                        if (beat_idx + 1 >= beats_total)
                            state <= S_DONE;
                        else
                            state <= S_READ_A_AR;
                    end
                end

                // ── Done ──
                S_DONE: begin
                    reg_status <= 1'b1;
                    state      <= S_IDLE;
                end
            endcase
        end
    end

endmodule
