// read_dma_core.sv — AXI4 Memory Read → AXI4-Stream Output
// Reads data from memory via AXI4 master, outputs as AXI4-Stream.
// AXI-Lite controller is auto-generated by vTen (generate_controller: true)
//
// Register Map (driven by auto-generated controller):
//   src_addr_lo/hi — source address [63:0]
//   length         — number of beats to transfer
//   ctrl           — bit[0] = start (pulse)
//   status         — bit[0] = done  (read-only)

module read_dma_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_src_addr_lo,
    input  logic [31:0] reg_src_addr_hi,
    input  logic [31:0] reg_length,
    input  logic        reg_ctrl,          // pulse: 1-cycle start trigger
    output logic [31:0] reg_status,        // read-only: bit[0] = done flag

    // ── AXI4 Master (SV interface) — memory read port ──
    vten_aximm_if.master mem_port,

    // ── AXI4-Stream Master — output data ──
    vten_axis_if.master  output_stream
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;

    // ── State machine ──
    typedef enum logic [2:0] {
        S_IDLE,
        S_AR,           // Issue AXI4 read address
        S_R,            // Wait for read data
        S_STREAM,       // Push data to AXI4-Stream
        S_DONE
    } state_t;

    state_t            state;
    logic [31:0]       beat_cnt;
    logic [DATA_W-1:0] data_buf;

    wire [63:0] src_addr = {reg_src_addr_hi, reg_src_addr_lo};

    // ── Main FSM ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state              <= S_IDLE;
            beat_cnt           <= '0;
            data_buf           <= '0;
            reg_status         <= '0;
            // AXI4 defaults
            mem_port.arvalid   <= 1'b0;
            mem_port.rready    <= 1'b0;
            // AXI4-Stream defaults
            output_stream.tvalid <= 1'b0;
            output_stream.tdata  <= '0;
            output_stream.tlast  <= 1'b0;
        end else begin
            case (state)
                S_IDLE: begin
                    output_stream.tvalid <= 1'b0;
                    if (reg_ctrl) begin
                        beat_cnt   <= '0;
                        reg_status <= '0;
                        if (reg_length == 0)
                            state <= S_DONE;
                        else
                            state <= S_AR;
                    end
                end

                S_AR: begin
                    mem_port.araddr  <= src_addr + (beat_cnt * BYTES_PER_BEAT);
                    mem_port.arlen   <= 8'd0;       // single beat
                    mem_port.arsize  <= $clog2(BYTES_PER_BEAT);
                    mem_port.arburst <= 2'b01;      // INCR
                    mem_port.arvalid <= 1'b1;
                    if (mem_port.arvalid && mem_port.arready) begin
                        mem_port.arvalid <= 1'b0;
                        mem_port.rready  <= 1'b1;
                        state <= S_R;
                    end
                end

                S_R: begin
                    if (mem_port.rvalid && mem_port.rready) begin
                        data_buf         <= mem_port.rdata;
                        mem_port.rready  <= 1'b0;
                        // Push to stream
                        output_stream.tdata  <= mem_port.rdata;
                        output_stream.tvalid <= 1'b1;
                        output_stream.tlast  <= (beat_cnt + 1 >= reg_length);
                        state <= S_STREAM;
                    end
                end

                S_STREAM: begin
                    if (output_stream.tvalid && output_stream.tready) begin
                        output_stream.tvalid <= 1'b0;
                        output_stream.tlast  <= 1'b0;
                        beat_cnt <= beat_cnt + 1;
                        if (beat_cnt + 1 >= reg_length)
                            state <= S_DONE;
                        else
                            state <= S_AR;
                    end
                end

                S_DONE: begin
                    reg_status <= 32'h1;
                    // Re-arm: a fresh start pulse restarts the transfer with the
                    // current register values (multi-config session replay).
                    // reg_ctrl must be a 1-cycle pulse (spec: pulse true) — a
                    // level-held ctrl would spuriously restart here and re-read
                    // an already-drained PUSH buffer (AXI4 DECERR).
                    if (reg_ctrl) begin
                        beat_cnt   <= '0;
                        reg_status <= '0;
                        if (reg_length != 0)
                            state <= S_AR;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

    // ── Tie-offs: AXI4 write channel (unused) ──
    assign mem_port.awaddr  = '0;
    assign mem_port.awlen   = '0;
    assign mem_port.awsize  = '0;
    assign mem_port.awburst = '0;
    assign mem_port.awvalid = 1'b0;
    assign mem_port.wdata   = '0;
    assign mem_port.wstrb   = '0;
    assign mem_port.wlast   = 1'b0;
    assign mem_port.wvalid  = 1'b0;
    assign mem_port.bready  = 1'b0;

endmodule
