// write_dma_core.sv — AXI4-Stream Input → AXI4 Memory Write
// Accepts data from AXI4-Stream, writes to memory via AXI4 master.
// AXI-Lite controller is auto-generated by vTen (generate_controller: true)
//
// Register Map (driven by auto-generated controller):
//   dst_addr_lo/hi — destination address [63:0]
//   length         — number of beats to transfer
//   ctrl           — bit[0] = start (pulse)
//   status         — bit[0] = done  (read-only)

module write_dma_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_dst_addr_lo,
    input  logic [31:0] reg_dst_addr_hi,
    input  logic [31:0] reg_length,
    input  logic        reg_ctrl,          // pulse: 1-cycle start trigger
    output logic [31:0] reg_status,        // read-only: bit[0] = done flag

    // ── AXI4-Stream Slave — input data ──
    vten_axis_if.slave   input_stream,

    // ── AXI4 Master (SV interface) — memory write port ──
    vten_aximm_if.master mem_port
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;

    // ── Tie-offs: AXI4 read channel (unused) ──
    assign mem_port.araddr  = '0;
    assign mem_port.arlen   = '0;
    assign mem_port.arsize  = '0;
    assign mem_port.arburst = '0;
    assign mem_port.arvalid = 1'b0;
    assign mem_port.rready  = 1'b0;

    // ── DMA Write Engine ──
    typedef enum logic [2:0] {
        S_IDLE,
        S_ACCEPT,       // Accept stream data
        S_AW,           // Issue AXI4 write address + data
        S_W,            // Wait for AW/W handshakes
        S_B,            // Wait for write response
        S_DONE
    } state_t;

    state_t            state;
    logic [63:0]       dst_addr;
    logic [31:0]       beats_left;
    logic [31:0]       beat_count;
    logic [DATA_W-1:0] data_latch;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state              <= S_IDLE;
            input_stream.tready <= 1'b0;
            mem_port.awvalid   <= 1'b0;
            mem_port.wvalid    <= 1'b0;
            mem_port.bready    <= 1'b0;
            reg_status         <= '0;
            beat_count         <= 0;
        end else begin
            case (state)
                S_IDLE: begin
                    input_stream.tready <= 1'b0;
                    if (reg_ctrl) begin
                        dst_addr   <= {reg_dst_addr_hi, reg_dst_addr_lo};
                        beats_left <= reg_length;
                        beat_count <= 0;
                        reg_status <= '0;
                        if (reg_length == 0)
                            state <= S_DONE;
                        else begin
                            state               <= S_ACCEPT;
                            input_stream.tready <= 1'b1;
                        end
                    end
                end

                S_ACCEPT: begin
                    if (input_stream.tvalid && input_stream.tready) begin
                        data_latch          <= input_stream.tdata;
                        input_stream.tready <= 1'b0;
                        state               <= S_AW;
                    end
                end

                S_AW: begin
                    mem_port.awaddr  <= dst_addr + beat_count * BYTES_PER_BEAT;
                    mem_port.awlen   <= 8'd0;
                    mem_port.awsize  <= $clog2(BYTES_PER_BEAT);
                    mem_port.awburst <= 2'b01;
                    mem_port.awvalid <= 1'b1;
                    mem_port.wdata   <= data_latch;
                    mem_port.wstrb   <= {BYTES_PER_BEAT{1'b1}};
                    mem_port.wlast   <= 1'b1;
                    mem_port.wvalid  <= 1'b1;
                    state            <= S_W;
                end

                S_W: begin
                    if (mem_port.awready && mem_port.awvalid)
                        mem_port.awvalid <= 1'b0;
                    if (mem_port.wready && mem_port.wvalid)
                        mem_port.wvalid <= 1'b0;

                    if ((!mem_port.awvalid || mem_port.awready) &&
                        (!mem_port.wvalid  || mem_port.wready)) begin
                        mem_port.awvalid <= 1'b0;
                        mem_port.wvalid  <= 1'b0;
                        mem_port.bready  <= 1'b1;
                        state            <= S_B;
                    end
                end

                S_B: begin
                    if (mem_port.bvalid && mem_port.bready) begin
                        mem_port.bready <= 1'b0;
                        beat_count      <= beat_count + 1;
                        beats_left      <= beats_left - 1;
                        if (beats_left == 1)
                            state <= S_DONE;
                        else begin
                            input_stream.tready <= 1'b1;
                            state               <= S_ACCEPT;
                        end
                    end
                end

                S_DONE: begin
                    reg_status <= 32'h1;
                    // Re-arm: a fresh start pulse re-latches address/length and
                    // restarts the write engine (multi-config session replay).
                    // reg_ctrl must be a 1-cycle pulse (spec: pulse true).
                    if (reg_ctrl) begin
                        dst_addr   <= {reg_dst_addr_hi, reg_dst_addr_lo};
                        beats_left <= reg_length;
                        beat_count <= 0;
                        reg_status <= '0;
                        if (reg_length != 0) begin
                            state               <= S_ACCEPT;
                            input_stream.tready <= 1'b1;
                        end
                    end
                end
            endcase
        end
    end

endmodule
