// mm_loopback_core.sv — AXI4 Memory-Mapped Loopback DUT
// Reads data from source address via AXI4 master, writes to destination address.
// AXI4-Lite controller is auto-generated by vTen (generate_controller: true)
//
// Register Map (driven by auto-generated controller):
//   ctrl       — bit[0] = start (pulse)
//   status     — bit[0] = done  (read-only)
//   src_addr_lo/hi — source address [63:0]
//   dst_addr_lo/hi — destination address [63:0]
//   length     — number of beats to transfer

module mm_loopback_core #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic clk,
    input  logic rst_n,

    // ── Registers (driven by auto-generated AXI-Lite controller) ──
    input  logic [31:0] reg_src_addr_lo,
    input  logic [31:0] reg_src_addr_hi,
    input  logic [31:0] reg_dst_addr_lo,
    input  logic [31:0] reg_dst_addr_hi,
    input  logic [31:0] reg_length,
    input  logic        reg_ctrl,          // pulse: 1-cycle start trigger
    output logic        reg_status,        // read-only: done flag

    // ── AXI4 Master (SV interface) — read port ──
    vten_aximm_if.master mem_in,

    // ── AXI4 Master (SV interface) — write port ──
    vten_aximm_if.master mem_out
);

    localparam int BYTES_PER_BEAT = DATA_W / 8;

    // ── State machine ──
    typedef enum logic [2:0] {
        S_IDLE,
        S_AR,           // Issue AXI4 read address
        S_R,            // Wait for read data
        S_AW,           // Issue AXI4 write address
        S_W,            // Send write data
        S_B,            // Wait for write response
        S_DONE
    } state_t;

    state_t            state;
    logic [31:0]       beat_cnt;
    logic [DATA_W-1:0] data_buf;

    wire [63:0] src_addr = {reg_src_addr_hi, reg_src_addr_lo};
    wire [63:0] dst_addr = {reg_dst_addr_hi, reg_dst_addr_lo};

    // ── Edge detection on reg_ctrl (level → pulse) ──
    logic reg_ctrl_d;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) reg_ctrl_d <= 1'b0;
        else        reg_ctrl_d <= reg_ctrl;
    end
    wire start_pulse = reg_ctrl & ~reg_ctrl_d;

    // ── Main FSM ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state      <= S_IDLE;
            beat_cnt   <= '0;
            data_buf   <= '0;
            reg_status <= 1'b0;
            // AXI4 defaults — read port
            mem_in.arvalid <= 1'b0;
            mem_in.rready  <= 1'b0;
            // AXI4 defaults — write port
            mem_out.awvalid <= 1'b0;
            mem_out.wvalid  <= 1'b0;
            mem_out.bready  <= 1'b0;
        end else begin
            case (state)
                S_IDLE: begin
                    if (start_pulse) begin
                        $display("[mm_core] START: src=%h dst=%h len=%0d",
                                 src_addr, dst_addr, reg_length);
                        state      <= S_AR;
                        beat_cnt   <= '0;
                        reg_status <= 1'b0;
                    end
                end

                S_AR: begin
                    mem_in.araddr  <= src_addr + (beat_cnt * BYTES_PER_BEAT);
                    mem_in.arlen   <= 8'd0;       // single beat
                    mem_in.arsize  <= $clog2(BYTES_PER_BEAT);
                    mem_in.arburst <= 2'b01;      // INCR
                    mem_in.arvalid <= 1'b1;
                    if (mem_in.arvalid && mem_in.arready) begin
                        mem_in.arvalid <= 1'b0;
                        mem_in.rready  <= 1'b1;
                        state <= S_R;
                    end
                end

                S_R: begin
                    if (mem_in.rvalid && mem_in.rready) begin
                        data_buf      <= mem_in.rdata;
                        mem_in.rready <= 1'b0;
                        state         <= S_AW;
                    end
                end

                S_AW: begin
                    mem_out.awaddr  <= dst_addr + (beat_cnt * BYTES_PER_BEAT);
                    mem_out.awlen   <= 8'd0;      // single beat
                    mem_out.awsize  <= $clog2(BYTES_PER_BEAT);
                    mem_out.awburst <= 2'b01;     // INCR
                    mem_out.awvalid <= 1'b1;
                    mem_out.wdata   <= data_buf;
                    mem_out.wstrb   <= {BYTES_PER_BEAT{1'b1}};
                    mem_out.wlast   <= 1'b1;
                    mem_out.wvalid  <= 1'b1;
                    state           <= S_W;
                end

                S_W: begin
                    if (mem_out.awready && mem_out.awvalid)
                        mem_out.awvalid <= 1'b0;
                    if (mem_out.wready && mem_out.wvalid)
                        mem_out.wvalid <= 1'b0;

                    if ((!mem_out.awvalid || mem_out.awready) &&
                        (!mem_out.wvalid  || mem_out.wready)) begin
                        mem_out.awvalid <= 1'b0;
                        mem_out.wvalid  <= 1'b0;
                        mem_out.bready  <= 1'b1;
                        state           <= S_B;
                    end
                end

                S_B: begin
                    if (mem_out.bvalid && mem_out.bready) begin
                        mem_out.bready <= 1'b0;
                        beat_cnt       <= beat_cnt + 1;
                        if (beat_cnt + 1 >= reg_length)
                            state <= S_DONE;
                        else
                            state <= S_AR;
                    end
                end

                S_DONE: begin
                    $display("[mm_core] DONE: %0d beats transferred", beat_cnt);
                    reg_status <= 1'b1;
                    state      <= S_IDLE;
                end

                default: state <= S_IDLE;
            endcase
        end
    end

    // ── Tie-offs: mem_in write channel (unused) ──
    assign mem_in.awaddr  = '0;
    assign mem_in.awlen   = '0;
    assign mem_in.awsize  = '0;
    assign mem_in.awburst = '0;
    assign mem_in.awvalid = 1'b0;
    assign mem_in.wdata   = '0;
    assign mem_in.wstrb   = '0;
    assign mem_in.wlast   = 1'b0;
    assign mem_in.wvalid  = 1'b0;
    assign mem_in.bready  = 1'b0;

    // ── Tie-offs: mem_out read channel (unused) ──
    assign mem_out.araddr  = '0;
    assign mem_out.arlen   = '0;
    assign mem_out.arsize  = '0;
    assign mem_out.arburst = '0;
    assign mem_out.arvalid = 1'b0;
    assign mem_out.rready  = 1'b0;

endmodule
