// mm_loopback_xrt_top.sv — Vitis-compatible top wrapper
// Maps ap_clk/ap_aresetn + s_axi_ctrl naming to the codegen wrapper ports.
// This module is the XO packaging top; for xsim, use mm_loopback directly.

module mm_loopback_xrt_top #(
    parameter DATA_W = 256,
    parameter ADDR_W = 64
)(
    input  logic ap_clk,
    input  logic ap_aresetn,

    // ── AXI4-Lite Slave: s_axi_ctrl ──
    input  logic [11:0]  s_axi_ctrl_awaddr,
    input  logic         s_axi_ctrl_awvalid,
    output logic         s_axi_ctrl_awready,
    input  logic [31:0]  s_axi_ctrl_wdata,
    input  logic [3:0]   s_axi_ctrl_wstrb,
    input  logic         s_axi_ctrl_wvalid,
    output logic         s_axi_ctrl_wready,
    output logic [1:0]   s_axi_ctrl_bresp,
    output logic         s_axi_ctrl_bvalid,
    input  logic         s_axi_ctrl_bready,
    input  logic [11:0]  s_axi_ctrl_araddr,
    input  logic         s_axi_ctrl_arvalid,
    output logic         s_axi_ctrl_arready,
    output logic [31:0]  s_axi_ctrl_rdata,
    output logic [1:0]   s_axi_ctrl_rresp,
    output logic         s_axi_ctrl_rvalid,
    input  logic         s_axi_ctrl_rready,

    // ── AXI4 Master: m_axi_mem_in ──
    output logic [ADDR_W-1:0]  m_axi_mem_in_awaddr,
    output logic [7:0]         m_axi_mem_in_awlen,
    output logic [2:0]         m_axi_mem_in_awsize,
    output logic [1:0]         m_axi_mem_in_awburst,
    output logic               m_axi_mem_in_awvalid,
    input  logic               m_axi_mem_in_awready,
    output logic [DATA_W-1:0]  m_axi_mem_in_wdata,
    output logic [DATA_W/8-1:0] m_axi_mem_in_wstrb,
    output logic               m_axi_mem_in_wlast,
    output logic               m_axi_mem_in_wvalid,
    input  logic               m_axi_mem_in_wready,
    input  logic [1:0]         m_axi_mem_in_bresp,
    input  logic               m_axi_mem_in_bvalid,
    output logic               m_axi_mem_in_bready,
    output logic [ADDR_W-1:0]  m_axi_mem_in_araddr,
    output logic [7:0]         m_axi_mem_in_arlen,
    output logic [2:0]         m_axi_mem_in_arsize,
    output logic [1:0]         m_axi_mem_in_arburst,
    output logic               m_axi_mem_in_arvalid,
    input  logic               m_axi_mem_in_arready,
    input  logic [DATA_W-1:0]  m_axi_mem_in_rdata,
    input  logic [1:0]         m_axi_mem_in_rresp,
    input  logic               m_axi_mem_in_rlast,
    input  logic               m_axi_mem_in_rvalid,
    output logic               m_axi_mem_in_rready,

    // ── AXI4 Master: m_axi_mem_out ──
    output logic [ADDR_W-1:0]  m_axi_mem_out_awaddr,
    output logic [7:0]         m_axi_mem_out_awlen,
    output logic [2:0]         m_axi_mem_out_awsize,
    output logic [1:0]         m_axi_mem_out_awburst,
    output logic               m_axi_mem_out_awvalid,
    input  logic               m_axi_mem_out_awready,
    output logic [DATA_W-1:0]  m_axi_mem_out_wdata,
    output logic [DATA_W/8-1:0] m_axi_mem_out_wstrb,
    output logic               m_axi_mem_out_wlast,
    output logic               m_axi_mem_out_wvalid,
    input  logic               m_axi_mem_out_wready,
    input  logic [1:0]         m_axi_mem_out_bresp,
    input  logic               m_axi_mem_out_bvalid,
    output logic               m_axi_mem_out_bready,
    output logic [ADDR_W-1:0]  m_axi_mem_out_araddr,
    output logic [7:0]         m_axi_mem_out_arlen,
    output logic [2:0]         m_axi_mem_out_arsize,
    output logic [1:0]         m_axi_mem_out_arburst,
    output logic               m_axi_mem_out_arvalid,
    input  logic               m_axi_mem_out_arready,
    input  logic [DATA_W-1:0]  m_axi_mem_out_rdata,
    input  logic [1:0]         m_axi_mem_out_rresp,
    input  logic               m_axi_mem_out_rlast,
    input  logic               m_axi_mem_out_rvalid,
    output logic               m_axi_mem_out_rready
);

    // ── Instantiate codegen wrapper with port renaming ──
    mm_loopback u_inner (
        .clk        (ap_clk),
        .rst_n      (ap_aresetn),

        // AXI4-Lite: s_axi_ctrl → s_axilite
        .s_axilite_awaddr  (s_axi_ctrl_awaddr),
        .s_axilite_awvalid (s_axi_ctrl_awvalid),
        .s_axilite_awready (s_axi_ctrl_awready),
        .s_axilite_wdata   (s_axi_ctrl_wdata),
        .s_axilite_wstrb   (s_axi_ctrl_wstrb),
        .s_axilite_wvalid  (s_axi_ctrl_wvalid),
        .s_axilite_wready  (s_axi_ctrl_wready),
        .s_axilite_bresp   (s_axi_ctrl_bresp),
        .s_axilite_bvalid  (s_axi_ctrl_bvalid),
        .s_axilite_bready  (s_axi_ctrl_bready),
        .s_axilite_araddr  (s_axi_ctrl_araddr),
        .s_axilite_arvalid (s_axi_ctrl_arvalid),
        .s_axilite_arready (s_axi_ctrl_arready),
        .s_axilite_rdata   (s_axi_ctrl_rdata),
        .s_axilite_rresp   (s_axi_ctrl_rresp),
        .s_axilite_rvalid  (s_axi_ctrl_rvalid),
        .s_axilite_rready  (s_axi_ctrl_rready),

        // AXI4 Master: m_axi_mem_in → m_axi_in
        .m_axi_in_awaddr   (m_axi_mem_in_awaddr),
        .m_axi_in_awlen    (m_axi_mem_in_awlen),
        .m_axi_in_awsize   (m_axi_mem_in_awsize),
        .m_axi_in_awburst  (m_axi_mem_in_awburst),
        .m_axi_in_awvalid  (m_axi_mem_in_awvalid),
        .m_axi_in_awready  (m_axi_mem_in_awready),
        .m_axi_in_wdata    (m_axi_mem_in_wdata),
        .m_axi_in_wstrb    (m_axi_mem_in_wstrb),
        .m_axi_in_wlast    (m_axi_mem_in_wlast),
        .m_axi_in_wvalid   (m_axi_mem_in_wvalid),
        .m_axi_in_wready   (m_axi_mem_in_wready),
        .m_axi_in_bresp    (m_axi_mem_in_bresp),
        .m_axi_in_bvalid   (m_axi_mem_in_bvalid),
        .m_axi_in_bready   (m_axi_mem_in_bready),
        .m_axi_in_araddr   (m_axi_mem_in_araddr),
        .m_axi_in_arlen    (m_axi_mem_in_arlen),
        .m_axi_in_arsize   (m_axi_mem_in_arsize),
        .m_axi_in_arburst  (m_axi_mem_in_arburst),
        .m_axi_in_arvalid  (m_axi_mem_in_arvalid),
        .m_axi_in_arready  (m_axi_mem_in_arready),
        .m_axi_in_rdata    (m_axi_mem_in_rdata),
        .m_axi_in_rresp    (m_axi_mem_in_rresp),
        .m_axi_in_rlast    (m_axi_mem_in_rlast),
        .m_axi_in_rvalid   (m_axi_mem_in_rvalid),
        .m_axi_in_rready   (m_axi_mem_in_rready),

        // AXI4 Master: m_axi_mem_out → m_axi_out
        .m_axi_out_awaddr  (m_axi_mem_out_awaddr),
        .m_axi_out_awlen   (m_axi_mem_out_awlen),
        .m_axi_out_awsize  (m_axi_mem_out_awsize),
        .m_axi_out_awburst (m_axi_mem_out_awburst),
        .m_axi_out_awvalid (m_axi_mem_out_awvalid),
        .m_axi_out_awready (m_axi_mem_out_awready),
        .m_axi_out_wdata   (m_axi_mem_out_wdata),
        .m_axi_out_wstrb   (m_axi_mem_out_wstrb),
        .m_axi_out_wlast   (m_axi_mem_out_wlast),
        .m_axi_out_wvalid  (m_axi_mem_out_wvalid),
        .m_axi_out_wready  (m_axi_mem_out_wready),
        .m_axi_out_bresp   (m_axi_mem_out_bresp),
        .m_axi_out_bvalid  (m_axi_mem_out_bvalid),
        .m_axi_out_bready  (m_axi_mem_out_bready),
        .m_axi_out_araddr  (m_axi_mem_out_araddr),
        .m_axi_out_arlen   (m_axi_mem_out_arlen),
        .m_axi_out_arsize  (m_axi_mem_out_arsize),
        .m_axi_out_arburst (m_axi_mem_out_arburst),
        .m_axi_out_arvalid (m_axi_mem_out_arvalid),
        .m_axi_out_arready (m_axi_mem_out_arready),
        .m_axi_out_rdata   (m_axi_mem_out_rdata),
        .m_axi_out_rresp   (m_axi_mem_out_rresp),
        .m_axi_out_rlast   (m_axi_mem_out_rlast),
        .m_axi_out_rvalid  (m_axi_mem_out_rvalid),
        .m_axi_out_rready  (m_axi_mem_out_rready)
    );

endmodule
